### ISSUE TITLE
Provide a Spark Streaming job construct on EMR Serverless

### ISSUE THREAD

**Issue by vgkowski** [awslabs/data-solutions-framework-on-aws#386]
Currently, implementing a Spark Streaming job on EMR Serverless requires additional tooling to implement streaming best practices. We can provide a construct similar to the `SparkEmrServerlessJob` but for streaming. Main features it should support:
 - Checkpointing the Spark state on a resilient storage
 - Graceful update of the Spark Streaming application. When deploying a new version of the Spark code, the construct should gracefully shutdown the current Spark Streaming job and then start the new one from the same checkpoint
 - automatically retry the Spark Streaming job when a failure is detected. The retry mechanism should have a maximum number of  retry, an exponential backoff retry mechanism and an alerting

**Comment by omar-diop** [comment]
Hi @vgkowski 

I'm currently exploring implementing Spark Structured Streaming on EMR Serverless and seeking to incorporate best practices, including job retry mechanisms.

You mentioned that additional tooling is required. I'm curious if you've discovered solutions or alternative approaches for implementing retry policies within the AWS ecosystem, perhaps utilizing services such as AWS Step Functions to efficiently manage repeated attempts.

Thank you!

**Comment by vgkowski** [comment]
EMR Serverless has released the streaming job feature with auto-retry, multi-az and log rotation

https://docs.aws.amazon.com/emr/latest/EMR-Serverless-UserGuide/jobs-streaming.html

Graceful shutdown is still missing. Is it a blocker for you @omar-diop ?

**Comment by vgkowski** [comment]
closing considering EMR Serverless release
