### ISSUE TITLE
Add option to DataLakeCatalog/DataCatalogDatabase to not create crawlers

### ISSUE THREAD

**Issue by karnik** [awslabs/data-solutions-framework-on-aws#491]
DataLakeCatalog/DataCatalogDatabase should have the option that the crawlers are not created automatically.

There are use cases (e.g. in the IoT area) where the tables have to be created manually. The data is then not added via a crawler, but manually via lambda functions.

**Comment by vgkowski** [comment]
Here you can find the parameter to disable the crawler creation in the [`DataLakeCatalog`](https://constructs.dev/packages/@cdklabs/aws-data-solutions-framework/v/1.2.0/api/DataLakeCatalogProps?lang=typescript&submodule=governance#property.autoCrawl) and the [`DataCatalogDatabase`](https://constructs.dev/packages/@cdklabs/aws-data-solutions-framework/v/1.2.0/api/DataCatalogDatabaseProps?lang=typescript&submodule=governance#property.autoCrawl)

**Comment by karnik** [comment]
Hi. Sorry, I missed that while reading the doc.

But I did notice one thing. When I read and tested this now, I made the assumption that an "undefined" variable would result in a false. However, the value defaults to true. 

I would suggest replacing the autoCrawl option with disableAutoCrawl and then defaulting it to false. I think that would be clearer.
