### ISSUE TITLE
Add support to MSK KRaft

### ISSUE THREAD

**Issue by armaseg** [awslabs/data-solutions-framework-on-aws#664]
AWS launched support for KRaft on new clusters on Amazon MSK starting from version 3.7. https://aws.amazon.com/blogs/big-data/introducing-support-for-apache-kafka-on-raft-mode-kraft-with-amazon-msk-clusters/ 

Currently, MSK Provisioned cluster depends on zookeeper, so if you try to deploy a new cluster using KRaft, you will get the following error

`Received response status [FAILED] from custom resource. Message returned: Error: Cannot read properties of undefined (reading 'split') TypeError: Cannot read properties of undefined (reading 'split'), at Runtime.onEventHandler [as handler] (file:///var/task/index.mjs:23:76), at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at P (/var/task/index.js:1:1756) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async Runtime.handler (/var/task/__entrypoint__.js:1:932)`

 In the future, the Apache Kafka community plans to remove the ZooKeeper mode entirely.

**Comment by lmouhib** [comment]
Already tracked in  #640. Closing this one as duplicate.
